version: "3"
services:
  api:
    image: fifa101/daal-daal:2
    depends_on:
      - postgres
    ports:
      - 80:8000
   
    environment:
      - DATABASE_HOSTNAME=${D_HOSTNAME}
      - DATABASE_PORT=${D_PORT}
      - DATABASE_PASSWORD=${D_PASSWORD}
      - DATABASE_NAME=${D_NAME}
      - DATABASE_USERNAME=${D_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  command: uvicorn app.main:app --host 0.0.0.0 --port 8000 

    

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
